### ISSUE TITLE
Optware partition size

### ISSUE THREAD

**Issue by REBELinBLUE** [BarakaAka1Only/OptWDMyCloud#1]
Just a note to add, I made the optware partition 256MB as in the screen shots. Today when trying to update plexpy it failed as the space needed to update was more than the available space due to the size of the repo.

I thankfully realised out that you can of course have plexpy on the main drive, doesn't need to be on the optware drive (obvious really) but might be worth adding a note

**Comment by BarakaAka1Only** [comment]
Yeah you can of course have Plexpy on one of the main HD's the main point behind this is python for Plexpy as the one on the OS fails due to some SSL method thing, as long as /opt with ipkg or even opkg is installed with python 2.7 your in business; having said that good to see things are working 👍

**Comment by REBELinBLUE** [comment]
Yeah I know, it was me asking on the WD forums before Christmas who prompted you to write this. 😉Thanks again!

Just thought it was worth mentioning that the plexpy repo is growing at a pace that having it on a 256MB partition may not be enough 😊
